CREATE TABLE moradores(
id BIGINT NOT NULL,
nome VARCHAR(150) NOT NULL,
cpf VARCHAR(11) NOT NULL UNIQUE,
numero VARCHAR(11) NOT NULL,
torre VARCHAR(10) NOT NULL,
apartamento VARCHAR(10) NOT NULL,

PRIMARY KEY(id)

);